### ISSUE TITLE
Crash when enabling video while camera is in use

### ISSUE THREAD

**Issue by ivananfruns** [DolbyIO/comms-sdk-unreal#103]
If you call the blueprint node "Enable Video" while any other application is gathering the camera input the editor or the build crashes with a fatal error. 

It would be good to check first if the camera is available and return false if it couldnt be enabled. 

**Specifications**

-   OS:  Windows 
-   Version:
    -   comms-sdk-unreal 1.0.0]

**Comment by kubaau** [comment]
@ivananfruns This was [fixed in a release of an underlying component](https://github.com/DolbyIO/comms-sdk-cpp/releases/tag/2.4.0-beta.3) recently and the fix will be available in the next plugin release (a matter of days). Thank you for the report (and the comms volume one :)).

**Comment by kubaau** [comment]
Will be fixed in 1.0.1.

**Comment by kubaau** [comment]
@ivananfruns Should be fixed in release 1.0.1. Please verify whether this solution is satisfactory or let us know if you would like to see some more explicit errors in this case.
