### ISSUE TITLE
Authentication (Access token) without a backend server

### ISSUE THREAD

**Issue by FabienLavocat** [DolbyIO/comms-sdk-unreal#21]
Provide a way to get an access token to authenticate the SDK without having to setup a backend server.
As a non-developer who is building an Unreal experience using visual script, I do not have the expertise and resources to deploy a backend service that would allow my Unreal game to retrieve an access token that is used to authenticate the plugin (and Dolby.io SDK).

**Comment by jfan-dolby** [comment]
security best practice requires developers to put up backend server and acquire token through that agent. But it doesn't mean we have to mandate developers to do that during onboarding. As long as we can state in production what is needed, we can make it easier for developers to do so through blueprints by implementing basic auth sequence. Our doc needs to be explicit about production recommendations.

**Comment by kubaau** [comment]
https://github.com/DolbyIO/comms-sdk-unreal/pull/22

**Comment by kubaau** [comment]
The issue itself is solved. The final comment of #22 will be addressed in #26.
