### ISSUE TITLE
Voice fonts support

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-unreal#273]
When available in the C++ SDK voice fonts support should be added, including as Blueprint nodes to set the voice font and to get the list of available voce fonts.

**Comment by djova-dolby** [comment]
Voice Fonts are available in the c++sdk as of 2.5.
https://api-references.dolby.io/comms-sdk-cpp/api/sdk/audio.html#_CPPv4N7dolbyio5comms10voice_fontE
https://api-references.dolby.io/comms-sdk-cpp/api/sdk/audio.html#_CPPv4N7dolbyio5comms18audio_capture_mode8standardE
https://api-references.dolby.io/comms-sdk-cpp/api/sdk/audio.html#_CPPv4N7dolbyio5comms8services11local_audio16set_capture_modeERKN18audio_capture_mode8standardE

**Comment by kubaau** [comment]
Will be available in 1.2.0-beta.2
