### ISSUE TITLE
EnableVideo ignores its parameter and always uses the system default video device

### ISSUE THREAD

**Issue by andreibazi** [DolbyIO/comms-sdk-unreal#279]
**Describe the bug**

The plugin exposes method `EnableVideo` which expects a `FDolbyIOVideoDevice` parameter representing the video device to use. However, regardless of the value of this parameter, video is always enabled using the system default video device. Changing the default video device on the system level makes the plugin/SDK reflect the change.

**Expected Behavior**

When providing a video device as a parameter to the `EnableVideo` method, that device should become the source of the video frames.

**Minimalistic code (recommended)**

A sample UE 5.1.1 project repository demonstrating the issue can be found [here](https://github.com/andreibazi/DolbyIOVirtualWorldsDebug).
This sample project will try to cycle through enabling video using each of the first 2 system video devices at a 5 second interval. However, after each `EnableVideo(Device)` call, the preview plane will display the system default webcam, ignoring the video device passed as a parameter and thus showcasing the issue.

To reproduce the issue without cloning the project:
- ensure your system has at least 2 video devices/webcams connected. Most laptops have a built-in camera, and to get a second one you can download [OBS Studio](https://obsproject.com/download) and use its Virtual Webcam feature;
- in a project containing the [1.1.0](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.0)release of the plugin, call `DolbyIOSubsystem->GetVideoDevices();` to get a list of available video devices;
- when `OnVideoDevicesReceived` returns the list, attempt to call `DolbyIOSubsystem->EnableVideo(Devices[1]);` - ensure the video device you're passing as a parameter is not the default one. Notice that despite this, the plugin will enable video using the system default device.

**Specifications**

-   OS: Windows 11 Pro 22H2 build 22621.1848 with Windows Feature Experience Pack 1000.22642.1000.0
-   Version:
    -   Unreal Engine 5.1.1;
    -   Dolby.io Virtual Worlds [1.1.0](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.0);
-  Tested on a laptop machine using three different video devices (integrated, external and OBS Virtual Camera);

**Comment by kubaau** [comment]
@andreibazi Easily reproducible. Thanks for the detailed report. Will investigate what is happening.

**Comment by kubaau** [comment]
@andreibazi The root cause has been found within an underlying component and the fix will be delivered this week.

**Comment by andreibazi** [comment]
Thank you! Looking forward to it.

**Comment by kubaau** [comment]
Fxied in release [1.1.1](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.1)
