### ISSUE TITLE
Extend FDolbyIOScreenshareSource to include a thumbnail

### ISSUE THREAD

**Issue by andreibazi** [DolbyIO/comms-sdk-unreal#280]
An application allowing screen sharing usually previews each possible source via a thumbnail image during the source selection step.
In a web app, this would be handled by the browser engine, but for a UE game/application, it would be great if the `FDolbyIOScreenshareSource` struct could be extended to provide a `Texture2D` preview of the screen/window and potentially another `Texture2D` representing the icon of the parent application.

**Comment by kubaau** [comment]
@andreibazi Unfortunately this will require some changes to an [underlying component](https://github.com/DolbyIO/comms-sdk-cpp) and can take some time. I will get back to you when I have a timeline for when this feature could be available.

**Comment by andreibazi** [comment]
Copy that, thank you!
