### ISSUE TITLE
Texture creation now happens after OnVideoTrackAdded

### ISSUE THREAD

**Issue by andreibazi** [DolbyIO/comms-sdk-unreal#319]
**Describe the bug**

`DolbyIOSubsystem->GetTexture(VideoTrackId)` now returns `nullptr` if called right away inside a function bound to `OnVideoTrackAdded` . This seems to happen because since the `1.1.1` release, texture creation happens some time after the event has fired. When calling `GetTexture(VideoTrackId)` ~500ms after the event, the texture is correctly returned most of the time.

**Expected Behavior**

Calling `DolbyIOSubsystem->GetTexture(VideoTrackId)` from inside a function bound to `OnVideoTrackAdded` should return a valid texture, without necessitating any waiting. This was the behavior in version `1.1.0` .

**Specifications**

- OS: Windows 11 Pro 22H2 build 22621.1848 with Windows Feature Experience Pack 1000.22642.1000.0
- Version:
    - Unreal Engine 5.2.1;
    - Dolby.io Virtual Worlds [1.1.1](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.1), [1.2.0-beta.2](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.2.0-beta.2);

**Comment by kubaau** [comment]
This will be fixed on Thursday in 1.1.2 and 1.2.0-beta.3 but I recommend using Bind Material instead of Get Texture if possible.

**Comment by kubaau** [comment]
@andreibazi Should be fixed in the aforementioned releases.

**Comment by kubaau** [comment]
@andreibazi The 1.1.2 release was previously made from the wrong commit so it was the same as 1.2.0-beta.3. This issue is now fixed. If you want to keep using version 1.1 I recommend redownloading 1.1.2 since it is more stable than the 1.2 betas.
