### ISSUE TITLE
Artifacts should be generated for all builds

### ISSUE THREAD

**Issue by kubaau** [DolbyIO/comms-sdk-unreal#35]
Currently it is only possible to download artifacts for builds happening after pushing to main. It would be more useful to have artifacts available for all builds, even if that means reducing the retention period.

**Comment by msobo1** [comment]
Artefact retention was set to 14 days. @kubaau perhaps we can decrease retention only for artefacts created by dev builds. What are current needs? 3 days is enough?

**Comment by kubaau** [comment]
Honestly even 1 day would be enough. Let's make it 2 as a happy medium 😂.

**Comment by msobo1** [comment]
Well, I am not going to insist :) 1 day sounds good, 2 days either.

**Comment by msobo1** [comment]
It was fixed into CCS-4456
