### ISSUE TITLE
Update to C++ SDK 2.6.*

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-unreal#360]
The C++ SDK has been updated with a new beta release, [2.6.0-beta.1](https://github.com/DolbyIO/comms-sdk-cpp/releases/tag/2.6.0-beta.1).

Update the plugin to use this version of the C++ SDK. While C++ is beta, the plugin should remain beta as well.

**Comment by kubaau** [comment]
This is already done on the develop branch, so 1.2.0-beta.7 will be released with SDK 2.6.
