### ISSUE TITLE
Memory leak while sharing a specific window

### ISSUE THREAD

**Issue by andreibazi** [DolbyIO/comms-sdk-unreal#361]
**Describe the bug**

Sharing a specific window (as opposed to an entire screen) will lead to a memory leak.

**Expected Behavior**

Memory is managed correctly while sharing specific windows.

**Minimalistic code (recommended)**

Steps to reproduce this issue with a vanilla UE project implementing the plugin (reproduced using `1.1.2` ,  `1.1.4` and `1.2.0-beta.6`):
- Get the `BP_DolbyIOStarter` blueprint up and running;
- Start PIE, select a specific window as the screen sharing source and start screen sharing;
- UE memory usage will quickly start rising, leading to a crash; 

**Specifications**

-   OS: Windows 11 Pro 22H2 build 22621.1848 with Windows Feature Experience Pack 1000.22642.1000.0
-   Version:
    -   Unreal Engine 5.2.1;
    -   Dolby.io Virtual Worlds 1.1.2, 1.1.4, 1.2.0-beta.6;

**Comment by kubaau** [comment]
I can confirm this issue is easy to reproduce. We will need a fix in the [underlying component](https://github.com/DolbyIO/comms-sdk-cpp) which shouldn't take too long with such an obvious error.

**Comment by kubaau** [comment]
Fixed in [1.1.5](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.1.5) and [1.2.0-beta.7](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.2.0-beta.7).
