### ISSUE TITLE
v1.2.0 don't package in shipping configuration

### ISSUE THREAD

**Issue by AntonIovbakDev** [DolbyIO/comms-sdk-unreal#411]
**Describe the bug**

Don't even package in shipping configuration

**Expected Behavior**

[Describe the expected behavior of the feature.]

**Specifications**

-   OS: Windows 10
-   Version:
    -   dolby v1.2.0
![Screenshot_1](https://github.com/DolbyIO/comms-sdk-unreal/assets/144774935/e97d93fe-143a-43a7-9347-5845e4c24cf9)

**Comment by AntonIovbakDev** [comment]
delete this
![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/144774935/36b5c6e8-2d6d-4331-828b-4c2755b4563b)

**Comment by kubaau** [comment]
Yes, this is the solution, it's a leftover mistake (similar for Mac and Linux). I will try to release this a 1.2.1 patch, but tomorrow is my last day at Dolby so if I don't get the chance, then this issue should be kept as known because it already provides the solution.

**Comment by AntonIovbakDev** [comment]
I wrote it so others could see it. Good luck in a new place! Thank you for your cooperation

**Comment by AntonIovbakDev** [comment]
Just curious does this dll not using somewhere in a plugin's code?

**Comment by kubaau** [comment]
Should be fixed in [1.2.1](https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.2.1). The dll is unnecessary, dvdnr.dll replaces it.
