### ISSUE TITLE
In a new version we have crash related with avformat-59.dll

### ISSUE THREAD

**Issue by AInsolence** [DolbyIO/comms-sdk-unreal#427]
**Describe the bug**

In a new version we have crash related with avformat-59.dll. Crash after starting UE client/server

**Expected Behavior**

no crash

**Minimalistic code (recommended)**

**Specifications**

-   OS: Windows 10
-   Version:
    -   1.2.4
![Dolby_6](https://github.com/DolbyIO/comms-sdk-unreal/assets/17539803/c3d47d82-af2b-43cb-8c18-8eaecfd8270c)

**Comment by djova-dolby** [comment]
Do you have the dll in the location from which it is trying to be loaded?

**Comment by djova-dolby** [comment]
Cannot reproduce locally with latest plugin. Dll is found in the required location in package.
