### ISSUE TITLE
cant see the dolby.io virtual world plugins blueprint folder in unreal engine 5.1.1

### ISSUE THREAD

**Issue by erenyeager2000** [DolbyIO/comms-sdk-unreal#428]
**cant see the dolby.io virtual world plugins blueprint folder**

i followed the installation process provided in the official dolby.io virtual world plugins in unreal engine 5 documentation but after installation the project files only contains c++ files of the plugins there are no blueprints of the plugins like for example "dolby.io starter" and others important blueprints

**Expected Behavior**

whenever we install the plugins, we can see the blueprint folder  for example "dolby.io starter" and others which are highly important

**Minimalistic code (recommended)**

[Please provide a link to a repository showing specifically the issue. It should only have the minimal footprint of your own implementation - something which does not requires any NDA.]

**Specifications**

-   OS: Windows
-   Version:11
    -   _for each libraries : name -> unreal engine 5.1.1 and visual studios, dolby.io virtual world plugins 1.1.0-beta.2
    -   comms-sdk-unreal-1.1.0-beta.1
    
![Screenshot 2023-12-15 060545](https://github.com/DolbyIO/comms-sdk-unreal/assets/123779144/03c21fae-9d54-4962-a93e-54d1049749f1)

    -   [...]

**Comment by djova-dolby** [comment]
Could you try using one of the latest relesaes like https://github.com/DolbyIO/comms-sdk-unreal/releases/tag/1.2.4 to see if the issue still reproduces?
