### ISSUE TITLE
Plugin descriptor contains wrong version

### ISSUE THREAD

**Issue by kubaau** [DolbyIO/comms-sdk-unreal#45]
The version in https://github.com/DolbyIO/comms-sdk-unreal/blob/main/DolbyIO/DolbyIO.uplugin#L4 is wrong. It should be 1.0 for now.

**Comment by jfan-dolby** [comment]
Please also update the `Category` to `Communications` to properly reflect the purpose of the plugin. `Media` can be misread as a Media player.

**Comment by kubaau** [comment]
#48
