### ISSUE TITLE
Untrusted developer issue when loading the project with the DolbyIO plugin enabled

### ISSUE THREAD

**Issue by adamallaf** [DolbyIO/comms-sdk-unreal#49]
Libraries affected:
1. UE4Editor-DolbyIO.dylib
2. libdvclient.dylib
3. libdolbyio_comms_media.dylib

**Comment by msobo1** [comment]
@adamallaf : please test with new artefacts created here: https://github.com/DolbyIO/comms-sdk-unreal/actions/runs/4075808510

**Comment by kubaau** [comment]
Please close if verified :)

**Comment by adamallaf** [comment]
The issue does not exist with the latest beta.
