### ISSUE TITLE
Clean up "supported environments" readme section

### ISSUE THREAD

**Issue by kubaau** [DolbyIO/comms-sdk-unreal#52]
Currently the "supported environments" section can be confusing as it states that we support UE 4.27 and 5.0.3, Windows 10 and macOS 12. It would be more applicable to mention that the supported operating systems for the plugin are:
- Windows 10+
- macOS:
  - UE 4.27: latest Mojave
  - UE 5: latest Monterey  
 
which are determined as being the highest common factor between UE and the C++ SDK (UE4 supports Windows 7, but SDK does not; SDK supports Mojave, but UE5 does not).

And that we support the following Unreal Engine versions: 4.27, 5.0, (soon) 5.1.

**Comment by Rishav1707** [comment]
Shall I work on this issue?
