### ISSUE TITLE
Enabling the video by a participant triggers participant added event on the other one

### ISSUE THREAD

**Issue by adamallaf** [DolbyIO/comms-sdk-unreal#61]
Steps to reproduce:
1. Create a call with two participants
2. the first participant enables his video
3. the second participant got a participant added event triggered.

My blueprints:
![on_added_on_left](https://user-images.githubusercontent.com/5655997/215744849-f6f599b1-58ee-4fe6-8b88-d32d8dc5ebe6.png)

![video_enable_disable](https://user-images.githubusercontent.com/5655997/215744872-47cd197b-8bef-40b7-9a9f-2bfe6556a8a7.png)

**Comment by kubaau** [comment]
test

**Comment by adamallaf** [comment]
Issue solved.
