### ISSUE TITLE
Shorten the readme

### ISSUE THREAD

**Issue by kubaau** [DolbyIO/comms-sdk-unreal#69]
The readme is very long and some of the information in it should land on GitHub pages or in a similar doc tool.

**Comment by dzeitman** [comment]
Does the Unreal Plugin Packaging supports a similar feature of optional asset and doc delivery that we use with Unity?
- We might also package and include getting started steps in a similar fashion.
- Give each version of Unreal Engine seems to be unique, perhaps each targeted SDK follows suit?
- Elsewhere, we've adopted using GitHub Pages to host SDK docs. 
- Perhaps this repo has the getting started guide in a docs folder and instance and that is served up with GitHub pages?    
- This slightly shifts the shared focus of presenting and maintaining SDK docs to the individual repo; with the intent that they would likely be more often updated and aligned and easy to access for the developer.

**Comment by jfan-dolby** [comment]
See branch doc-github-page for an implementation using docusaurus
