### ISSUE TITLE
Invalid metadata in the plugin's DLL

### ISSUE THREAD

**Issue by adamallaf** [DolbyIO/comms-sdk-unreal#71]
The plugin's dynamic library does not contain valid metadata.

![image](https://user-images.githubusercontent.com/5655997/216595829-8906e14d-1c8b-4065-a785-17548681ef88.png)

**Comment by kubaau** [comment]
@msobo1 This will be much easier to fix post-build. Unreal's automated plugin builder creates a dummy HostProject to build the plugin in and that dummy HostProject does not have any copyright entries and to add them would require us to modify engine code.

**Comment by kubaau** [comment]
@adamallaf Please also verify if this is a "problem" on macOS and add the appropriate label if it is.

**Comment by adamallaf** [comment]
Does not affect MacOS.

**Comment by adamallaf** [comment]
I believe this information can be set in project settings -> project -> description

Set my project description like this:
![image](https://user-images.githubusercontent.com/5655997/216640281-5fec3356-0991-432a-a2e8-dfb7f6f31d2d.png)

and the built DLL contains data like:
![image](https://user-images.githubusercontent.com/5655997/216640446-f1fdf4eb-9e5b-4bac-9fb5-58fba6f3262c.png)

**Comment by adamallaf** [comment]
Also can be edited from a config ini file
![image](https://user-images.githubusercontent.com/5655997/216641135-d164f572-1d06-498b-82e8-0a3ddd3af062.png)

**Comment by kubaau** [comment]
But those are project settings, not plugin settings. There is no project when packaging the plugin. More specifically, there is the HostProject project which is basically a dummy defined in the engine's automation tools.

**Comment by adamallaf** [comment]
I managed to pass the data from DefaultGame.ini to the output DLL with this workaround, I created a dummy project and placed the plugin in it's Plugins directory so the project directory structure looks like this:

```bash
~/Documents/Unreal Projects/aproject
$ ls *
aproject.uproject

Config:
DefaultEditor.ini  DefaultEngine.ini  DefaultGame.ini  FilterPlugin.ini

Plugins:
dummy_plugin/

```

then I built it with UBT as follows:
```PowerShell
& "C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\DotNET\UnrealBuildTool.exe" UE4Editor Win64 Development `
-Project="C:\Users\johnn\Documents\Unreal Projects\aproject\aproject.uproject" `
-plugin="C:\Users\johnn\Documents\Unreal Projects\aproject\Plugins\dummy_plugin\dummy_plugin.uplugin" `
-iwyu -noubtmakefiles -nohotreload -log="C:\Users\johnn\UBT-UE4Editor-Win64-Development.txt"
```

I think there should be an easier way to do that, but I could not find anything in unreal engine's documentation.
Or we can still try to build it with CMake.

**Comment by kubaau** [comment]
I honestly don't know enough about this sort of stuff so could you please coordinate with @msobo1 on how it could be addressed?

**Comment by kubaau** [comment]
Closing as unnecessary. Will monitor situation if proven otherwise.
